name: PHP CI/CD

on:
  workflow_dispatch:
  schedule:
        # Runs every day at 2:30 PM UTC
        - cron: '19 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql
          coverage: none

      # 3️⃣ Install dependencies
      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      # 4️⃣ Run tests (optional)
      - name: Run PHPUnit tests
        run: |
          if [ -f "vendor/bin/phpunit" ]; then
            vendor/bin/phpunit --testdox
          else
            echo "No tests found."
          fi

      # 5️⃣ Upload artifact for deployment
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-sample-app
          path: |
            src/
            index.php
            vendor/
            composer.json
            composer.lock

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      deployments: write  

    steps:
      # 1️⃣ Checkout code (needed for deployment action)
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Create Deployment record
      - name: Create Deployment
        id: deploy
        uses: chrnorm/deployment-action@releases/v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: production
          description: "Deploying main branch"
          payload: '{"run_id": "${{ github.run_id }}"}'

      # 3️⃣ Immediately mark Deployment as SUCCESS
      - name: Set Deployment Status
        uses: chrnorm/deployment-status@releases/v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment-id: ${{ steps.deploy.outputs.deployment_id }}
          state: success
          environment-url: "https://your-app-url.com"

